function addRating(value,pageType){if(value==-1)trackGAEvent("RatingTracking","ATFRateClicked",value);else trackGAEvent("RatingTracking","RatingSelected",value);if(pageType=="ATTRACTION"){var attractionId=$("#attractionId").val();window.location.href=domainRoot+"/add-review?star="+value+"&source=ATTRACTION&value="+attractionId;}
else if(pageType=="DESTINATION"||pageType=="PLACES"){var placeCode=$("#destPlaceCode").val();window.location.href=domainRoot+"/add-review?star="+value+"&source=destination&value="+placeCode;}
else if(pageType=="STATE"||pageType=="COUNTRY"){var stateCode=$("#destPlaceCode").val();window.location.href=domainRoot+"/add-review?star="+value+"&source="+pageType+"&value="+stateCode;}
else if(pageType=="ATTRACTIONVE"){var attrId=attractionId;var url=domainRoot+"/web/ajax/addAllRating.hdfy?placeCode="+attrId+"&rating="+value+"&pageType="+pageType;$.ajax({type:"GET",url:url,success:function(response){if(!loginDict["promptShown"])
window.location.href=domainRoot+"/userLocation.html?type=rating";}});}}
function openPrelogin(text,source){var modal=$("#preloginModal");modal.find("#myModalLabel").html("");modal.find("#myModalLabel").html(text);$("#preloginModal").modal("toggle");trackGAEvent("UGCTracking","preloginModal",source);if(!isEmpty(source))updatePreloginSource(source);}
function updatePreloginSource(loginSource){if($("#preloginSource").length>0)$("#preloginSource").val(loginSource);else{$("#preloginModal").append('<input type="hidden" value="'+loginSource+'" id="preloginSource" />');}}
function genericUserLogin(data,response){var obj=JSON.parse(data);if($("#comingFrom").val()=="Coming_From_Pdf"){loginDict["promptShown"]=obj.promptShown;downloadPdf();}
else if($("#preloginSource").val()=="RatingButtonClicked"){saveRating(loginDict["starPageType"],loginDict["entityId"]);}
else if($("#preloginSource").val()=="WishlistButtonClicked"){toggleWishlist(loginDict["wishlistPageType"]);if(!obj.promptShown)
window.location.href=domainRoot+"/userLocation.html?type=wishlist";else
window.location.reload();}
else if($("#preloginSource").val()=="addQuestionButtonClicked"){loginDict["promptShown"]=obj.promptShown;submitQuestion();}
else if($("#preloginSource").val()=="individualAddQuestionClicked"){loginDict["promptShown"]=obj.promptShown;submitQuestionIndividualPage();}
else if($("#preloginSource").val()=="addAnswerButtonClicked"){loginDict["promptShown"]=obj.promptShown;submitAnswer();}
else if($("#preloginSource").val()=="commentAnswerButtonClicked"){loginDict["promptShown"]=obj.promptShown;submitAnswerComment();}
else if($("#preloginSource").val()=="voteAnswerButtonClicked"){loginDict["promptShown"]=obj.promptShown;voteAnswer();}
else if($("#preloginSource").val()=="addReviewButtonClicked"){loginDict["promptShown"]=obj.promptShown;$("#genericModalHtml").show().html("<p class='text1'> Logged in succesfully. Refreshing page. </p>");submitReview();}
else if($("#preloginSource").val()=="VisitedButtonClicked"){toggleVisited();if(!obj.promptShown)
window.location.href=domainRoot+"/userLocation.html?type=visited";else
window.location.reload();}
else if($("#preloginSource").val()=="addRecentlyVisited"){window.location.href=domainRoot+"/recentlyVisited.html";}
else if($("#preloginSource").val()=="redirectAfterLogin"){window.location.replace(getParameterByName("redirectUrl"));}
else if(!obj.promptShown){window.location.href=domainRoot+"/userLocation.html";}
else{$("#genericModalHtml").show().html("<p class='text1'> Logged in succesfully. Refreshing page. </p>");window.location.hash='';window.location.reload();}}
function facebookLogin(){FB.login(function(response){trackGAEvent("UGCTracking","FacebookLoginDataReceived",$("#preloginSource").val());var fbToken=response.authResponse.accessToken;if(response.authResponse){$("#genericModal").modal("toggle");$("#genericModalHtml").show().html("<p class='text1'> Logged in succesfully, refreshing page... </p>");var loginFields="?fields=email,id,first_name,last_name,name,locale,gender,location,hometown,work";FB.api('/me'+loginFields,function(response){$.get(domainRoot+"/rest/userProfile/loginUserViaFB.hdfy?fbResponse="+encodeURIComponent(JSON.stringify(getFBResponseCleaned(response,fbToken))),function(data2,response2){genericUserLogin(data2,response2);trackGAEvent("UGCTracking","FacebookLoginSuccessful",$("#preloginSource").val());});});}},{scope:'public_profile,email',auth_type:'rerequest'});trackGAEvent("UGCTracking","FacebookLoginButtonClicked",$("#preloginSource").val());}
function googleLogin(){auth2.signIn().then(function(){trackGAEvent("UGCTracking","GoogleLoginDataReceived",$("#preloginSource").val());$("#genericModal").modal("toggle");$("#genericModalHtml").show().html("<p class='text1'> Logging in. Please Wait. </p>");var profile=googleGetInfo();$.get(domainRoot+"/rest/userProfile/loginUserViaGoogle.hdfy?googleResponse="+encodeURIComponent(JSON.stringify(getGoogleResponseCleaned(profile)))+"&googleImage="+encodeURIComponent(profile.getImageUrl()),function(data2,response2){genericUserLogin(data2,response2);trackGAEvent("UGCTracking","GoogleLoginSuccessful",$("#preloginSource").val());});});trackGAEvent("UGCTracking","GoogleLoginButtonClicked",$("#preloginSource").val());}
function googleOnetapLogin(response){let eventLabel=$("#pageType").val();var profile=getGoogleOnetapResponseCleaned(response);$.get(domainRoot+"/rest/userProfile/loginUserViaGoogle.hdfy?googleResponse="+encodeURIComponent(JSON.stringify(profile))+"&googleImage="+encodeURIComponent(profile.image_URL),function(data2,response2){trackGAEvent("LoginTracking","GoogleOneTapSuccess",eventLabel);genericUserLogin(data2,response2);});}
function logout(){$.get(domainRoot+"/rest/userProfile/logoutUser.hdfy",function(data2,response2){window.location.reload();});}
function submitReview(){if(!isLoggedIn()){openPrelogin("Login to submit your Review","addReviewButtonClicked");return;}
var reviewType=$("#newReview").attr("data-reviewType");var reviewTypeId=$("#newReview").attr("data-reviewTypeId");var rating=$(".review-block input[type='radio'][name='rating'][checked='checked']").attr("value");var dataText=$("#newReview").val();var datasize=dataText.length;var voteType=$("#newReview").attr("data-voteType");var placeCode=$("#destPlaceCode").val();var reviewTypeName=$("#newReview").attr("data-reviewTypeName");trackGAEvent("RatingTracking","AddReviewClicked",reviewType+' | '+reviewTypeId);if(datasize<140){$(".errorReviewMessage").remove();$("#newReview").after("<p class='errorReviewMessage'>Please enter atleast 140 characters</p>");return;}
var isValid=validateDataInput(dataText);if(isValid=="DATA_INCORRECT"){showNotification("Please enter correct data");return;}
if(isValid=="NOT_LOGGED_IN"){}
if(isValid=="CORRECT"){$("#newReviewCommentContainer").append(getLoadingHtml());var url=domainRoot+"/web/ajax/addReview.hdfy";if(reviewType.toUpperCase()=='PLACES')reviewType='DESTINATION';var dataArray={reviewType:reviewType,reviewTypeId:reviewTypeId,reviewText:dataText,destinationRating:rating,attractionVoteType:voteType,placeCode:placeCode,reviewTypeName:reviewTypeName};$.ajax({type:"POST",url:url,data:dataArray,success:function(dataResp,response){var resp=dataResp;trackGAEvent("RatingTracking","ReviewSubmitted",reviewType+' | '+reviewTypeId);if(resp.error){$(".error-message p").text("You have already submitted a reivew for "+reviewTypeName);window.location.href="/review-success?source="+reviewType+"&value="+reviewTypeId.toLowerCase()+"&ratingExist=true";}
else window.location.href="/review-success?source="+resp.review.reviewType+"&value="+resp.review.reviewTypeId.toLowerCase();},error:function(){showNotification("Unable to add data right now, please try again later.");}});}}
function saveRating(entityType,entityId){var star=$("input[type='radio'][name='rating'][checked='checked']").attr("value");if(!isLoggedIn()){openPrelogin("Login to Add your Rating","RatingButtonClicked");loginDict["starValue"]=star;loginDict["entityId"]=entityId;loginDict["starPageType"]=entityType;return;}
trackGAEvent("RatingTracking","RatingSubmitted",star);var url=domainRoot+"/web/ajax/addAllRating.hdfy?placeCode="+entityId+"&rating="+star+"&pageType="+entityType.toUpperCase();$.ajax({type:"GET",url:url,success:function(response){window.location.href="/review-success?source="+entityType+"&value="+entityId.toLowerCase()+"&reviewSubmitted=false";}});}
function showReviewBox(entityType,entityId){trackGAEvent("RatingTracking","AddReviewClicked",entityType+" | "+entityId)
$(".hf-cash-section").hide('slow');$(".review-section").show("fast");}
function checkAndSubmitReview(){var text_length=$("#newReview").val().length;if(text_length>350)
$('#textareaFeedback').html('Max Limit: 350');else if(text_length<140)
$('#textareaFeedback').html('<span style="color: red">Please enter atleast 140 characters</span>');else submitReview();}
function trackGAQnaActions(category){pageType=$("#pageType").val();trackGAEvent("QuestionTracking",category,pageType);}
function initGoogleOneTap(){let promptDelay=10*1000;let eventLabel=$("#pageType").val();setTimeout(function(){google.accounts.id.initialize({client_id:'676916581715-sjlqseut80pjaivjfkqga21jjfsbl0fj.apps.googleusercontent.com',callback:googleOnetapLogin,});google.accounts.id.prompt((notification)=>{trackGAEvent("LoginTracking","GoogleOneTapPrompt",eventLabel);if(notification.isNotDisplayed()||notification.isSkippedMoment()){}});sessionStorage.removeItem('oneTapPrompt');},promptDelay);}
function submitQuestion(){trackGAEvent("QuestionTracking","Add_Question",pageType);trackGAEvent("UGCTracking","addQuestionButtonClicked","");var pageType=$("#newQuestion").attr("pageType");var parentId="-1";var dataText=$("#newQuestion").val();var datasize=dataText.length;var type="q";if(datasize<35){$(".errorReviewMessage").remove();$("#newQuestion").after("<p class='errorReviewMessage'>Please enter atleast 35 characters</p>");return;}
if(pageType=="ATTRACTION"){var destination=$("#newQuestion").attr("questionattractionId");}
else if(pageType=="COUNTRY"){var destination=$("#newQuestion").attr("questionattractionId");}
else{var destination=$("#destPlaceCode").val();}
if(!isLoggedIn()){openPrelogin("Login to submit your question","addQuestionButtonClicked");return;}
var isValid=validateDataInput(dataText);if(isValid=="DATA_INCORRECT"){showNotification("Please enter correct data");return;}
if(isValid=="NOT_LOGGED_IN"){}
if(isValid=="CORRECT"&&pageType!="ATTRACTION"){var dataArray={parentId:parentId,dataText:dataText,destination:destination,type:type,pageType:pageType};addQnaData(dataArray);$("#newQuestionContainer").append(getLoadingHtml());}
else if(isValid=="CORRECT"&&pageType=="ATTRACTION"){var attractionName=$("#newQuestion").attr("questionattractionName");var dataArray={parentId:parentId,dataText:dataText,destination:destination,type:type,attractionName:attractionName};addQnaDataAttraction(dataArray);$("#newQuestionContainer").append(getLoadingHtml());}
else if(isValid=="CORRECT"&&pageType=="COUNTRY"){var dataArray={parentId:parentId,dataText:dataText,destination:destination,type:type,pageType:pageType};addQnaData(dataArray);$("#newQuestionContainer").append(getLoadingHtml());}}
function submitAnswer(){trackGAEvent("AnswerTracking","Add_Answer",pageType);var parentId=$("#questionData").val();var dataText=$("#newAnswer").val();var pageType=$("#newAnswer").attr("pageType")
var datasize=dataText.length;var destination=$("#destPlaceCode").val();var type="a";if(datasize<35){$(".errorReviewMessage").remove();$("#newAnswer").after("<p class='errorReviewMessage'>Please enter atleast 35 characters</p>");return;}
if(!isLoggedIn()){openPrelogin("Login to submit your answer","addAnswerButtonClicked");return;}
var isValid=validateDataInput(dataText);if(isValid=="DATA_INCORRECT"){showNotification("Please enter correct data");return;}
if(isValid=="NOT_LOGGED_IN"){}
if(isValid=="CORRECT"){var dataArray={parentId:parentId,dataText:dataText,destination:destination,type:type,pageType:pageType};addQnaData(dataArray);}}
function submitAnswerComment(){parentId=commentDict['parentId'];dataText=commentDict['dataText'];destination=commentDict['destination'];commentInput=commentDict['commentInput'];var datasize=dataText.length;var type="c";if(datasize<2){$(".errorReviewMessage").remove();commentInput.after("<p class='errorReviewMessage'>Please enter atleast 2 characters</p>");return;}
if(!isLoggedIn()){openPrelogin("Login to submit your comment","commentAnswerButtonClicked");return;}
pageType=$("#pageType").val();trackGAEvent("AnswerTracking","Add_Answer_Comment",pageType);var isValid=validateDataInput(dataText);if(isValid=="DATA_INCORRECT"){showNotification("Please enter correct data");return;}
if(isValid=="NOT_LOGGED_IN"){}
if(isValid=="CORRECT"){$(".errorReviewMessage").remove();var dataArray={parentId:parentId,dataText:dataText,destination:destination,type:type};addQnaData(dataArray);}}
function voteAnswer(){var voteBtnPressed=$(".upvote-answer[data-action='vote']");var voted=voteBtnPressed.hasClass("voted");var dataId=voteBtnPressed.attr("data-parentId");var url="";voteData={userID:readCookie("token").split('|')[0],userHash:readCookie("token").split('|')[1],dataId:dataId,}
if(!voted){url="/rest/qna/voteQnA.hdfy";voteData.voteType="upvote";}else{url="/rest/qna/unvoteQnA.hdfy";voteData.voteType="downvote";}
$.ajax({type:"POST",url:url,data:voteData,success:function(data,response){curVote=voteBtnPressed.siblings(".votes").text();if(voteData.voteType==="upvote"){voteBtnPressed.addClass("voted");voteBtnPressed.find("svg").replaceWith(getSpriteString("like-blue"));voteBtnPressed.siblings(".votes").text(parseInt(curVote)+1);}else{voteBtnPressed.removeClass("voted");voteBtnPressed.find("svg").replaceWith(getSpriteString("like"));voteBtnPressed.siblings(".votes").text(parseInt(curVote)-1);}
if(!loginDict["promptShown"])window.location.href=domainRoot+"/userLocation.html?type=upvote";$("#preloginModal, #genericModal").modal("hide");},error:function(){},});voteBtnPressed.attr("data-action","");}
function openAskQuestionpage(type,placeCode){pageType=$("#pageType").val();trackGAEvent("QuestionTracking","AskQuestionATFButton_"+pageType,placeCode);window.location.href=domainRoot+"/askQuestion.html?type="+type+"&placeCode="+placeCode;}
function openProfilePage(){userId=readCookie("token").split('|')[0];window.location.href=domainRoot+"/profile/"+userId;}